### ISSUE TITLE
elastic exited with code 78

### ISSUE THREAD

**Issue by mhabsaoui** [openminted/omtd-docker#1]
Hi,

After a docker-compose up of the omtd-docker, on the deploy docker logs we got an error concerning elastic and elasticsearch2 containers as follow :

> CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                       PORTS                                                                     NAMES
> f359f17941f2        omtddocker_tomcat                                     "catalina.sh run"        18 minutes ago      Up 17 minutes                0.0.0.0:8080->8080/tcp                                                    tomcat
> 
> 2e0d10076102        docker.elastic.co/elasticsearch/elasticsearch:5.2.2   "/bin/bash bin/es-..."   18 minutes ago      Exited (78) 17 minutes ago                                                                             elasticsearch2
> 
> e60529ed0b20        omtddocker_db                                         "docker-entrypoint..."   18 minutes ago      Up 18 minutes                0.0.0.0:5432->5432/tcp                                                    postgres
> 
> 25375120b5f6        rmohr/activemq:5.14.0-alpine                          "/bin/sh -c 'bin/a..."   18 minutes ago      Up 18 minutes                1883/tcp, 5672/tcp, 8161/tcp, 61613-61614/tcp, 0.0.0.0:61616->61616/tcp   jms
> 
> dc0fc6a64967        docker.elastic.co/elasticsearch/elasticsearch:5.2.2   "/bin/bash bin/es-..."   18 minutes ago      Exited (78) 17 minutes elastic

On the elastic containers logs :

> elasticsearch2    | [2017-07-12T09:04:10,580][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
jms               |  INFO | jolokia-agent: Using policy access restrictor classpath:/jolokia-access.xml
elastic           | [2017-07-12T09:04:13,029][INFO ][o.e.n.Node               ] initialized
elastic           | [2017-07-12T09:04:13,030][INFO ][o.e.n.Node               ] [uf-86Ak] starting ...
elastic           | [2017-07-12T09:04:13,253][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: ac:f0:2a:1d:6a:7c:08:9a
elastic           | [2017-07-12T09:04:13,337][INFO ][o.e.t.TransportService   ] [uf-86Ak] publish_address {172.18.0.3:9300}, bound_addresses {0.0.0.0:9300}
elastic           | [2017-07-12T09:04:13,355][INFO ][o.e.b.BootstrapChecks    ] [uf-86Ak] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elastic           | ERROR: bootstrap checks failed
elastic           | max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elastic           | [2017-07-12T09:04:13,362][INFO ][o.e.n.Node               ] [uf-86Ak] stopping ...
elastic           | [2017-07-12T09:04:13,513][INFO ][o.e.n.Node               ] [uf-86Ak] stopped
elastic           | [2017-07-12T09:04:13,515][INFO ][o.e.n.Node               ] [uf-86Ak] closing ...
elastic           | [2017-07-12T09:04:13,560][INFO ][o.e.n.Node               ] [uf-86Ak] closed
elasticsearch2    | [2017-07-12T09:04:14,068][INFO ][o.e.n.Node               ] initialized
elasticsearch2    | [2017-07-12T09:04:14,068][INFO ][o.e.n.Node               ] [wJzfrSp] starting ...
elasticsearch2    | [2017-07-12T09:04:14,250][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes: ef:45:19:72:3d:d6:bf:51
elasticsearch2    | [2017-07-12T09:04:14,315][INFO ][o.e.t.TransportService   ] [wJzfrSp] publish_address {172.18.0.5:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch2    | [2017-07-12T09:04:14,321][INFO ][o.e.b.BootstrapChecks    ] [wJzfrSp] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elasticsearch2    | ERROR: bootstrap checks failed
elasticsearch2    | max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch2    | [2017-07-12T09:04:14,339][INFO ][o.e.n.Node               ] [wJzfrSp] stopping ...
elastic exited with code 78
elasticsearch2    | [2017-07-12T09:04:14,401][INFO ][o.e.n.Node               ] [wJzfrSp] stopped
elasticsearch2    | [2017-07-12T09:04:14,401][INFO ][o.e.n.Node               ] [wJzfrSp] closing ...
elasticsearch2    | [2017-07-12T09:04:14,409][INFO ][o.e.n.Node               ] [wJzfrSp] closed
elasticsearch2 exited with code 78

On the tomcat logs too :

> tomcat            | java.net.UnknownHostException: **elastic**: Temporary failure in name resolution
tomcat            | 	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
tomcat            | 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
tomcat            | 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
tomcat            | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
tomcat            | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
tomcat            | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
tomcat            | 	at java.net.InetAddress.getByName(InetAddress.java:1076)
tomcat            | 	at eu.openminted.registry.core.configuration.ElasticConfiguration.client(ElasticConfiguration.java:53)
tomcat            | 	at eu.openminted.registry.core.configuration.ElasticConfiguration$$EnhancerBySpringCGLIB$$b2d7ac06.CGLIB$client$0(<generated>)
tomcat            | 	at eu.openminted.registry.core.configuration.ElasticConfiguration$$EnhancerBySpringCGLIB$$b2d7ac06$$FastClassBySpringCGLIB$$264ebe08.invoke(<generated>)
tomcat            | 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
tomcat            | 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:318)
tomcat            | 	at eu.openminted.registry.core.configuration.ElasticConfiguration$$EnhancerBySpringCGLIB$$b2d7ac06.client(<generated>)
tomcat            | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tomcat            | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
tomcat            | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tomcat            | 	at java.lang.reflect.Method.invoke(Method.java:498)
tomcat            | 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
tomcat            | 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
tomcat            | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
tomcat            | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
tomcat            | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
tomcat            | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
tomcat            | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:305)
tomcat            | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
tomcat            | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:301)
tomcat            | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
tomcat            | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
tomcat            | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:834)
tomcat            | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
tomcat            | 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
tomcat            | 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
tomcat            | 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
tomcat            | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
tomcat            | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
tomcat            | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
tomcat            | 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
tomcat            | 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
tomcat            | 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
tomcat            | 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
tomcat            | 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
tomcat            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
tomcat            | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
tomcat            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
tomcat            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
tomcat            | 	at java.lang.Thread.run(Thread.java:748)

Is it an already known issue ?

PS: I've searched and found tweaks ( [https://github.com/elastic/elasticsearch/issues/21523](url) )  about _service elasticsearch is not keep running_   and  _vm.max_map_count_

Thanks.

**Comment by courado** [comment]
In the docker-compose version I use the deprecated version of elastic and this was fixed with (this)[https://www.elastic.co/guide/en/elasticsearch/reference/5.0/vm-max-map-count.html]

However we switched to Docker swarm compose, I don't know if they still need the system setting, however, it is a small change to be made.
